#!/usr/bin/env python3
"""
Pulls student-facing files (seminar slides + weekly worksheet) out of the TA
bundle and into this site's content/ folder, then refreshes the auto-generated
materials section for each week on index.qmd (the site is one long page).

Usage:
    python3 tools/sync_materials.py [--source /path/to/ta_edit]

Run this any time the TA bundle is regenerated (e.g. after `make share-ta`)
or a new worksheet is added, then re-render the site.

What this script will NOT touch:
- Any prose, headings, or the quick-link table at the top of index.qmd.
- The "Case briefing (shared document)" section under each week — that
  link is set once by hand and left alone here.
- case-NN.pdf and prep-NN.md — not published to students by design.
"""

import argparse
import re
import shutil
import sys
from pathlib import Path

SITE_ROOT = Path(__file__).resolve().parent.parent
DEFAULT_SOURCE = SITE_ROOT.parent / "ta_edit"
INDEX_PATH = SITE_ROOT / "index.qmd"

# (week number, session slug)
SESSIONS = [
    (1, "01-introduction-transitions"),
    (2, "02-policy-process-streams"),
    (3, "03-policy-process-institutions"),
    (4, "04-governance-theories"),
    (5, "05-power-politics-change"),
    (6, "06-industrial-welfare-state"),
    (7, "07-environmental-governance"),
    (8, "08-digital-revolution"),
    (9, "09-climate-transition"),
    (10, "10-demographic-migration"),
    (11, "11-ai-automation"),
    (12, "12-synthesis-polycrisis"),
]


def sync_marker(num: int) -> tuple[str, str]:
    tag = f"week-{num:02d}"
    return (
        f"<!-- SYNC:START:{tag} (auto-generated by tools/sync_materials.py — do not hand-edit between these markers) -->",
        f"<!-- SYNC:END:{tag} -->",
    )


def find_worksheet(ta_dir: Path) -> Path | None:
    candidates = sorted(
        p
        for p in ta_dir.glob("*worksheet*.docx")
        if not p.name.startswith("~$")
    )
    return candidates[0] if candidates else None


def build_materials_block(slides_ok: bool, worksheet_src: Path | None, slug: str, num: int) -> str:
    lines = ["### Seminar slides"]
    if slides_ok:
        lines.append(f"- [Download slides (PDF)](content/{slug}/slides-{num:02d}.pdf)")
    else:
        lines.append('<span class="missing-note">Not posted yet — check back closer to the seminar.</span>')

    lines.append("")
    lines.append("### Worksheet")
    if worksheet_src:
        lines.append(f"- [Download worksheet (Word)](content/{slug}/{worksheet_src.name})")
    else:
        lines.append('<span class="missing-note">Not posted yet — check back closer to the seminar.</span>')

    return "\n".join(lines)


def sync_session(num: int, slug: str, source_root: Path, index_text: str, dry_run: bool) -> tuple[str, str]:
    ta_dir = source_root / "sessions" / slug / "ta"
    content_dir = SITE_ROOT / "content" / slug
    report = []

    slides_src = ta_dir / f"slides-{num:02d}.pdf"
    slides_ok = slides_src.exists()
    if slides_ok and not dry_run:
        content_dir.mkdir(parents=True, exist_ok=True)
        shutil.copy2(slides_src, content_dir / slides_src.name)
    report.append(f"slides: {'ok' if slides_ok else 'MISSING'}")

    worksheet_src = find_worksheet(ta_dir) if ta_dir.exists() else None
    if worksheet_src and not dry_run:
        content_dir.mkdir(parents=True, exist_ok=True)
        shutil.copy2(worksheet_src, content_dir / worksheet_src.name)
    report.append(f"worksheet: {'ok (' + worksheet_src.name + ')' if worksheet_src else 'MISSING'}")

    start, end = sync_marker(num)
    materials = build_materials_block(slides_ok, worksheet_src, slug, num)
    pattern = re.compile(re.escape(start) + r".*?" + re.escape(end), re.DOTALL)
    replacement = f"{start}\n{materials}\n{end}"

    if pattern.search(index_text):
        updated_text = pattern.sub(replacement, index_text)
        report.append("index.qmd: updated" if updated_text != index_text else "index.qmd: unchanged")
    else:
        updated_text = index_text
        report.append(f"index.qmd: WARNING sync markers for week-{num:02d} not found, section left untouched")

    return f"Week {num:02d} ({slug}): " + ", ".join(report), updated_text


def main():
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument(
        "--source",
        type=Path,
        default=DEFAULT_SOURCE,
        help=f"Path to the ta_edit bundle (default: {DEFAULT_SOURCE})",
    )
    parser.add_argument(
        "--dry-run",
        action="store_true",
        help="Report what would happen without copying files or writing index.qmd",
    )
    args = parser.parse_args()

    if not args.source.exists():
        print(f"error: source folder not found: {args.source}", file=sys.stderr)
        sys.exit(1)

    if not INDEX_PATH.exists():
        print(f"error: {INDEX_PATH} not found", file=sys.stderr)
        sys.exit(1)

    index_text = INDEX_PATH.read_text()
    original_text = index_text

    for num, slug in SESSIONS:
        line, index_text = sync_session(num, slug, args.source, index_text, args.dry_run)
        print(line)

    if not args.dry_run and index_text != original_text:
        INDEX_PATH.write_text(index_text)


if __name__ == "__main__":
    main()
